baseURL = 'https://skyelynwaddell.github.io/'
languageCode = 'en-us'
title = 'Skyesblog'

publishDir = "public"  # Make sure this line is present

paginate = 10

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    category = "categories"
    author = "authors"
