baseURL = 'https://skyelynwaddell.github.io/'
languageCode = 'en-us'
title = 'Skyesblog'

publishDir = "public"  # Make sure this line is present

[pagination] 
  pagerSize = 10

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    category = "categories"
    author = "authors"


[markup]
  [markup.highlight]
    noClasses = false  # Set to false to use classes
    guessSyntax = true
    codeFences = false  # Disable Hugo’s automatic syntax highlighting
    hl_Lines = ""       # Remove any highlighting lines
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    tabWidth = 4
