name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/skyesblog  # Change to the skyesblog directory
          ${RUNNER_TEMP}/hugo  # Run Hugo to build the site

      - name: Verify Build Output
        run: |
          ls -la ${GITHUB_WORKSPACE}/skyesblog/public  # List contents of the public directory to verify it exists

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          # Check if the public directory exists and is not empty
          if [ -d "${GITHUB_WORKSPACE}/skyesblog/public" ] && [ "$(ls -A ${GITHUB_WORKSPACE}/skyesblog/public)" ]; then
            # Copy built files to the root of the GitHub Pages repo
            cp -R ${GITHUB_WORKSPACE}/skyesblog/public/* ${GITHUB_WORKSPACE}/
          else
            echo "Public directory is missing or empty, aborting deployment."
            exit 1
          fi
          
          cd ${GITHUB_WORKSPACE}/skyesblog
          git config user.name 'skyelynwaddell'
          git config user.email 'dillonleewaddell@gmail.com'
          git add .
          git commit -m 'Deploy to GitHub Pages'
          # Push to the GitHub Pages repo using GITHUB_TOKEN for authentication
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/skyelynwaddell/skyelynwaddell.github.io.git main
