name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/skyesblog  # Change to the skyesblog directory
          ${RUNNER_TEMP}/hugo  # Run Hugo to build the site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          # Remove existing content in the public folder (which is the main directory for GitHub Pages)
          rm -rf ${GITHUB_WORKSPACE}/skyesblog/public/*
          
          # Copy built files to the public folder
          cp -R ${GITHUB_WORKSPACE}/skyesblog/public/* ${GITHUB_WORKSPACE}/skyesblog/
          
          cd ${GITHUB_WORKSPACE}/skyesblog
          git config user.name 'skyelynwaddell'
          git config user.email 'dillonleewaddell@gmail.com'
          git add .
          git commit -m 'Deploy to GitHub Pages'
          # Push to the GitHub Pages repo using GITHUB_TOKEN for authentication
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/skyelynwaddell/skyelynwaddell.github.io.git main
